defmodule Temporal.Api.Enums.V1.WorkflowTaskFailedCause do
  @moduledoc false

  use Protobuf, enum: true, syntax: :proto3, protoc_gen_elixir_version: "0.13.0"

  field :WORKFLOW_TASK_FAILED_CAUSE_UNSPECIFIED, 0
  field :WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_COMMAND, 1
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES, 2
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES, 3
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES, 4
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES, 5
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES, 6
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES, 7
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES, 8
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES, 9
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES, 10
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES, 11
  field :WORKFLOW_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID, 12
  field :WORKFLOW_TASK_FAILED_CAUSE_RESET_STICKY_TASK_QUEUE, 13
  field :WORKFLOW_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE, 14
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES, 15
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES, 16
  field :WORKFLOW_TASK_FAILED_CAUSE_FORCE_CLOSE_COMMAND, 17
  field :WORKFLOW_TASK_FAILED_CAUSE_FAILOVER_CLOSE_COMMAND, 18
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE, 19
  field :WORKFLOW_TASK_FAILED_CAUSE_RESET_WORKFLOW, 20
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_BINARY, 21
  field :WORKFLOW_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID, 22
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES, 23
  field :WORKFLOW_TASK_FAILED_CAUSE_NON_DETERMINISTIC_ERROR, 24
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_MODIFY_WORKFLOW_PROPERTIES_ATTRIBUTES, 25
  field :WORKFLOW_TASK_FAILED_CAUSE_PENDING_CHILD_WORKFLOWS_LIMIT_EXCEEDED, 26
  field :WORKFLOW_TASK_FAILED_CAUSE_PENDING_ACTIVITIES_LIMIT_EXCEEDED, 27
  field :WORKFLOW_TASK_FAILED_CAUSE_PENDING_SIGNALS_LIMIT_EXCEEDED, 28
  field :WORKFLOW_TASK_FAILED_CAUSE_PENDING_REQUEST_CANCEL_LIMIT_EXCEEDED, 29
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_UPDATE_WORKFLOW_EXECUTION_MESSAGE, 30
  field :WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_UPDATE, 31
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_NEXUS_OPERATION_ATTRIBUTES, 32
  field :WORKFLOW_TASK_FAILED_CAUSE_PENDING_NEXUS_OPERATIONS_LIMIT_EXCEEDED, 33
  field :WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_NEXUS_OPERATION_ATTRIBUTES, 34
  field :WORKFLOW_TASK_FAILED_CAUSE_FEATURE_DISABLED, 35
end

defmodule Temporal.Api.Enums.V1.StartChildWorkflowExecutionFailedCause do
  @moduledoc false

  use Protobuf, enum: true, syntax: :proto3, protoc_gen_elixir_version: "0.13.0"

  field :START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED, 0
  field :START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS, 1
  field :START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_NAMESPACE_NOT_FOUND, 2
end

defmodule Temporal.Api.Enums.V1.CancelExternalWorkflowExecutionFailedCause do
  @moduledoc false

  use Protobuf, enum: true, syntax: :proto3, protoc_gen_elixir_version: "0.13.0"

  field :CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED, 0
  field :CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND, 1
  field :CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_NAMESPACE_NOT_FOUND, 2
end

defmodule Temporal.Api.Enums.V1.SignalExternalWorkflowExecutionFailedCause do
  @moduledoc false

  use Protobuf, enum: true, syntax: :proto3, protoc_gen_elixir_version: "0.13.0"

  field :SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED, 0
  field :SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND, 1
  field :SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_NAMESPACE_NOT_FOUND, 2
  field :SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_SIGNAL_COUNT_LIMIT_EXCEEDED, 3
end

defmodule Temporal.Api.Enums.V1.ResourceExhaustedCause do
  @moduledoc false

  use Protobuf, enum: true, syntax: :proto3, protoc_gen_elixir_version: "0.13.0"

  field :RESOURCE_EXHAUSTED_CAUSE_UNSPECIFIED, 0
  field :RESOURCE_EXHAUSTED_CAUSE_RPS_LIMIT, 1
  field :RESOURCE_EXHAUSTED_CAUSE_CONCURRENT_LIMIT, 2
  field :RESOURCE_EXHAUSTED_CAUSE_SYSTEM_OVERLOADED, 3
  field :RESOURCE_EXHAUSTED_CAUSE_PERSISTENCE_LIMIT, 4
  field :RESOURCE_EXHAUSTED_CAUSE_BUSY_WORKFLOW, 5
  field :RESOURCE_EXHAUSTED_CAUSE_APS_LIMIT, 6
  field :RESOURCE_EXHAUSTED_CAUSE_PERSISTENCE_STORAGE_LIMIT, 7
  field :RESOURCE_EXHAUSTED_CAUSE_CIRCUIT_BREAKER_OPEN, 8
end

defmodule Temporal.Api.Enums.V1.ResourceExhaustedScope do
  @moduledoc false

  use Protobuf, enum: true, syntax: :proto3, protoc_gen_elixir_version: "0.13.0"

  field :RESOURCE_EXHAUSTED_SCOPE_UNSPECIFIED, 0
  field :RESOURCE_EXHAUSTED_SCOPE_NAMESPACE, 1
  field :RESOURCE_EXHAUSTED_SCOPE_SYSTEM, 2
end