name: Update Sources

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Setup elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.14.x
          otp-version: 25.x

      - name: Setup protoc-gen-elixir
        id: protobuf
        run: |
          mix escript.install hex protobuf --force
          
      - name: Init repository
        id: init-repo
        run: make init
          
      - name: get latest tags
        id: tags
        run: |
          echo "current_tag=$(git describe --abbrev=0 --tags)" >> "$GITHUB_OUTPUT"
          echo "new_tag=$(cd src/temporalio_api && git describe --tags `git rev-list --tags --max-count=1`)" >> "$GITHUB_OUTPUT"

      - name: Get latest versions and update protocol buffers
        id: get-and-update
        if: ${{ steps.tags.outputs.current_tag != steps.tags.outputs.new_tag }}
        run: make

      - name: Create Pull Request
        if: ${{ steps.tags.outputs.current_tag != steps.tags.outputs.new_tag }}
        uses: peter-evans/create-pull-request@v5
        with: 
          branch: upgrade-on-upstream
          base: main
          delete-branch: true
          title: 'New Upstream Version'
          assignees: mruoss
          body: |
            There is a new tag ${{ steps.tags.outputs.new_tag }} in the [upstream repository][1] 
            
            [1]: https://github.com/temporalio/api
          draft: false
          labels: |
            release

